from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.menu_principal, name='menu_principal'),  # Ruta para el menú principal
    path('crear_genero/', views.crear_genero, name='crear_genero'),
    path('generos/', views.generos, name='generos'),
    path('generos/editar/<int:id>/', views.crear_genero, name='genero_editar'),  # Reutilizamos la vista de crear para editar
    path('genero/eliminar/<int:id>/', views.eliminar_genero, name='genero_eliminar'),
    path('crear_estatus_usuario/', views.crear_estatus_usuario, name='crear_estatus_usuario'),
    path('estatus_usuario/', views.estatus_usuario, name='estatus_usuario'),
    path('crear_empresa/', views.crear_empresa, name='crear_empresa'),
    path('empresas/', views.empresas, name='empresas'),
    path('crear_sucursal/', views.crear_sucursal, name='crear_sucursal'),
    path('sucursales/', views.sucursales, name='sucursales'),
    path('crear_rol/', views.crear_rol, name='crear_rol'),
    path('roles/', views.roles, name='roles'),
    path('crear_menu/', views.crear_menu, name='crear_menu'),
    path('menus/', views.crear_menu, name='menus'),
    path('menus/editar/<int:id>/', views.crear_menu, name='menu_editar'),
    path('menu/eliminar/<int:id>/', views.eliminar_menu, name='menu_eliminar'),
    path('crear_modulo/', views.crear_modulo, name='crear_modulo'),
    path('modulos/', views.crear_modulo, name='modulos'),
    path('modulos/editar/<int:id>/', views.crear_modulo, name='modulo_editar'),
    path('modulo/eliminar/<int:id>/', views.eliminar_modulo, name='modulo_eliminar'),
    path('crear_opcion/', views.crear_opcion, name='crear_opcion'),
    path('opciones/', views.crear_opcion, name='opciones'),
    path('opciones/editar/<int:id>/', views.crear_opcion, name='opcion_editar'),
    path('opcion/eliminar/<int:id>/', views.eliminar_opcion, name='opcion_eliminar'),
    path('crear_rol_opcion/', views.crear_rol_opcion, name='crear_rol_opcion'),
    path('roles_opciones/', views.roles_opciones, name='roles_opciones'),
    path('crear_usuario_rol/', views.crear_usuario_rol, name='crear_usuario_rol'),
    path('usuarios_roles/', views.usuarios_roles, name='usuarios_roles'),
    path('crear_usuario_pregunta/', views.crear_usuario_pregunta, name='crear_usuario_pregunta'),
    path('usuarios_preguntas/', views.usuarios_preguntas, name='usuarios_preguntas'),
    path('tipo_accesos/', views.tipo_accesos, name='tipo_accesos'),
    path('bitacora_accessos/', views.bitacora_accesos, name='bitacora_accessos'),
    path('crear_estado_civil/', views.crear_estado_civil, name='crear_estado_civil'),
    path('estados_civiles/', views.estados_civiles, name='estados_civiles'),
    path('estados_civiles/editar/<int:id>/', views.crear_estado_civil, name='estado_civil_editar'), 
    path('estado_civil/eliminar/<int:id>/', views.eliminar_estado_civil, name='estado_civil_eliminar'),
    path('crear_tipo_documento/', views.crear_tipo_documento, name='crear_tipo_documento'),
    path('tipos_documentos/', views.tipos_documentos, name='tipos_documentos'),
    path('tipos_documentos/editar/<int:id>/', views.crear_tipo_documento, name='tipo_documento_editar'), 
    path('tipo_documento/eliminar/<int:id>/', views.eliminar_tipo_documento, name='tipo_documento_eliminar'),
    path('crear_persona/', views.crear_persona, name='crear_persona'),
    path('personas/', views.personas, name='personas'),
    path('personas/editar/<int:id>/', views.crear_persona, name='persona_editar'), 
    path('persona/eliminar/<int:id>/', views.eliminar_persona, name='persona_eliminar'),

    
]