# Generated by Django 4.2.1 on 2024-08-31 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=30)),
                ('password_cantidad_mayusculas', models.IntegerField(default=0)),
                ('password_cantidad_minusculas', models.IntegerField(default=0)),
                ('password_cantidad_caracteres_especiales', models.IntegerField(default=0)),
                ('password_cantidad_caducidad_dias', models.IntegerField(default=0)),
                ('password_cantidad_numeros', models.IntegerField(default=0)),
                ('password_tamano', models.IntegerField(default=0)),
                ('password_intentos_antes_de_bloquear', models.IntegerField(default=0)),
                ('password_cantidad_preguntar_validar', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=203)),
                ('frecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(max_length=203)),
            ],
        ),
        migrations.CreateModel(
            name='EstatusUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('frecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=203)),
                ('frecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(max_length=203)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=203)),
                ('frecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(max_length=203)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden_menu', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=203)),
                ('frecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(max_length=203)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden_menu', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=203)),
                ('frecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(max_length=203)),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden_menu', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=203)),
                ('frecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(max_length=203)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=203)),
                ('frecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(max_length=203)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=203)),
                ('frecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(max_length=203)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('password', models.CharField(max_length=30)),
                ('ultima_fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('intentos_de_acceso', models.IntegerField(default=0)),
                ('ultima_fecha_cambio_password', models.DateTimeField(blank=True, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=100, null=True)),
                ('requiere_cambiar_password', models.BooleanField(default=False)),
                ('fotografia', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=203)),
                ('frecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(max_length=203)),
                ('estatus_usuario', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.estatususuario')),
                ('genero', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.genero')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=203)),
                ('frecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(max_length=203)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.rol')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=100)),
                ('respuesta', models.CharField(max_length=100)),
                ('orden_pregunta', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=203)),
                ('frecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(max_length=203)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RolOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alta', models.BooleanField(default=True)),
                ('bajo', models.BooleanField(default=True)),
                ('cambio', models.BooleanField(default=True)),
                ('imprimir', models.BooleanField(default=True)),
                ('exportar', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(max_length=203)),
                ('frecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(max_length=203)),
                ('opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.opcion')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.rol')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.modulo'),
        ),
    ]
