# Generated by Django 5.1 on 2024-08-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='frecha_modificacion',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='estatususuario',
            old_name='frecha_creacion',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='estatususuario',
            old_name='frecha_modificacion',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='frecha_modificacion',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='frecha_modificacion',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='modulo',
            old_name='frecha_modificacion',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='opcion',
            old_name='frecha_modificacion',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='frecha_modificacion',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='rolopcion',
            old_name='frecha_modificacion',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='sucursal',
            old_name='frecha_modificacion',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='frecha_modificacion',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='usuariopregunta',
            old_name='frecha_modificacion',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='usuariorol',
            old_name='frecha_modificacion',
            new_name='fecha_modificacion',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='usuario_creacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='usuario_modificacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='estatususuario',
            name='usuario_creacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='estatususuario',
            name='usuario_modificacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='genero',
            name='usuario_creacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='genero',
            name='usuario_modificacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='menu',
            name='usuario_creacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='menu',
            name='usuario_modificacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='usuario_creacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='usuario_modificacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='usuario_creacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='usuario_modificacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='rol',
            name='usuario_creacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='rol',
            name='usuario_modificacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='rolopcion',
            name='usuario_creacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='rolopcion',
            name='usuario_modificacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='usuario_creacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='usuario_modificacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_creacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_modificacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='usuariopregunta',
            name='usuario_creacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='usuariopregunta',
            name='usuario_modificacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='usuario_creacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='usuario_modificacion',
            field=models.CharField(default='admin', max_length=203),
        ),
    ]
