# Generated by Django 5.1 on 2024-10-12 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_frecha_modificacion_empresa_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.CharField(default='admin', max_length=203)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.CharField(default='admin', max_length=203)),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('http_user_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('accion', models.CharField(blank=True, max_length=100, null=True)),
                ('sistema_operativo', models.CharField(blank=True, max_length=100, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=100, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('sesion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.usuario')),
                ('tipo_acceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.tipoacceso')),
            ],
        ),
    ]
