# Generated by Django 4.2.16 on 2024-11-10 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usuario_groups_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
    ]
