# Generated by Django 4.2.16 on 2024-11-11 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_usuario_is_active_remove_usuario_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='users.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='users.sucursal'),
            preserve_default=False,
        ),
    ]
