# Generated by Django 4.2.16 on 2024-11-11 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_sucursal_empresa_alter_usuario_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
    ]
