# Generated by Django 4.2.16 on 2024-11-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_usuario_groups_remove_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='usuario_modificacion',
            field=models.CharField(blank=True, max_length=203, null=True),
        ),
        migrations.AlterField(
            model_name='estatususuario',
            name='usuario_modificacion',
            field=models.CharField(blank=True, max_length=203, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='usuario_modificacion',
            field=models.CharField(blank=True, max_length=203, null=True),
        ),
    ]
