# Generated by Django 4.2.16 on 2024-11-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_empresa_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatususuario',
            name='usuario_creacion',
            field=models.CharField(blank=True, max_length=203, null=True),
        ),
    ]
