# Generated by Django 4.2.16 on 2024-11-12 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_persona_fecha_modificacion_and_more'),
        ('users', '0011_alter_estatususuario_usuario_creacion'),
    ]

    operations = [
    ]
