# Generated by Django 4.2.16 on 2024-11-13 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20241112_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='usuario_modificacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='rol',
            name='usuario_modificacion',
            field=models.CharField(default='admin', max_length=203),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.empresa'),
        ),
        migrations.AlterField(
            model_name='tipoacceso',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipoacceso',
            name='usuario_modificacion',
            field=models.CharField(blank=True, max_length=203, null=True),
        ),
    ]
