# Generated by Django 4.2.16 on 2024-11-13 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_estatuscuenta_statuscuenta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldocuenta',
            old_name='estatus_cuenta',
            new_name='status_cuenta',
        ),
    ]
