# Generated by Django 4.2.16 on 2024-11-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_empresa_usuario_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_creacion',
            field=models.CharField(blank=True, max_length=203, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_modificacion',
            field=models.CharField(blank=True, max_length=203, null=True),
        ),
    ]
