# Generated by Django 4.2.16 on 2024-11-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_usuario_usuario_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='accion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='browser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='direccion_ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='dispositivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='http_user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='sesion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bitacoraacceso',
            name='sistema_operativo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
