# Generated by Django 4.2.16 on 2024-11-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_estatus_cuenta_saldocuenta_status_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomovimientocxc',
            name='operacion_cuenta_corriente',
            field=models.IntegerField(default=1),
        ),
    ]
