# Generated by Django 4.2.16 on 2024-11-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_tipomovimientocxc_operacion_cuenta_corriente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomovimientocxc',
            name='operacion_cuenta_corriente',
            field=models.IntegerField(choices=[(2, 'Restar'), (1, 'Sumar')], default=1),
        ),
    ]
