# Generated by Django 4.2.16 on 2024-11-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_movimientocuenta_valor_movimiento_pagador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldocuenta',
            name='creditos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saldocuenta',
            name='debitos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saldocuenta',
            name='saldo_anterior',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tipomovimientocxc',
            name='operacion_cuenta_corriente',
            field=models.IntegerField(choices=[(2, 'Restar'), (1, 'Sumar')], default=1),
        ),
    ]
