CREATE USER analisis WITH PASSWORD 'analisis';
GRANT ALL PRIVILEGES ON DATABASE analisis TO analisis;
GRANT CONNECT ON DATABASE analisis TO analisis;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO analisis;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO analisis;
